from __future__ import annotations

from typing import Final

INTENT_SCHEMA: Final[dict[str, tuple[str, ...]]] = {
    "exit": (),
    "greeting": (),
    "chat": (),
    "get_time": (),
    "get_date": (),
    "advice_time": ("topic",),
    "convert_timezone": ("query",),
    "open_app": ("app",),
    "minimize": (),
    "maximize": (),
    "restore": (),
    "close": (),
    "focus": ("name",),
    "move_window": (),
    "resize_window": (),
    "volume_up": (),
    "volume_down": (),
    "set_volume": ("level",),
    "get_volume": (),
    "brightness_up": (),
    "brightness_down": (),
    "set_brightness": ("level",),
    "get_brightness": (),
    "volume_control": (),
    "brightness_control": (),
    "window_control": (),
    "list_processes": (),
    "kill_process": ("name",),
    "kill_pid": ("pid",),
    "check_process": ("name",),
    "list_files": (),
    "create_folder": ("name",),
    "create_file": ("name",),
    "delete": ("name",),
    "move": ("name",),
    "copy": ("name",),
    "search": ("name",),
    "file_info": ("name",),
    "file_manager": ("action",),
    "process_manager": ("action",),
    "run_command": ("command",),
    "run_python": ("file",),
    "run_code": ("file",),
    "open_cmd": (),
    "open_powershell": (),
    "screenshot": (),
    "take_screenshot": (),
    "play_music": (),
    "stop_music": (),
    "play_youtube": ("video",),
    "search_youtube": ("query",),
    "get_weather": ("city",),
    "get_news": ("category",),
    "lookup_word": ("word",),
    "get_crypto_price": ("symbol", "currency"),
    "check_price_alert": ("direction", "target_price", "symbol", "currency"),
    "schedule_task": ("delay_seconds",),
    "evaluate_trigger": ("query",),
    "apply_rules": ("query",),
    "resume_music": (),
    "next_track": (),
    "previous_track": (),
    "play_by_mood": ("mood",),
    "play_artist": ("artist",),
    "play_playlist": ("genre",),
}

AVAILABLE_INTENTS: Final[list[str]] = list(INTENT_SCHEMA.keys())
LLM_CLASSIFIER_INTENTS: Final[list[str]] = [name for name in AVAILABLE_INTENTS if name != "lookup_word"]
LLM_CLASSIFIER_INTENTS_SET: Final[frozenset[str]] = frozenset(LLM_CLASSIFIER_INTENTS)

REQUIRED_SLOTS: Final[dict[str, tuple[str, ...]]] = {
    "open_app": ("app",),
    "set_volume": ("level",),
    "set_brightness": ("level",),
    "lookup_word": ("word",),
}
