import { invoke } from '@tauri-apps/api/core';
import { marked } from 'marked';
import hljs from 'highlight.js';
import 'highlight.js/styles/github-dark.css';
import { JarvisApi, type ChatMessage, type VoiceState } from './api/jarvisApi';
import { store, type AppState } from './services/store';
import './css/styles.css';

marked.use({ renderer: { code(token) { const text = typeof token === 'string' ? token : token.text; const lang = typeof token === 'string' ? '' : token.lang; const language = lang && hljs.getLanguage(lang) ? lang : 'plaintext'; return `<pre class="code-card"><button class="copy-code">Copy</button><code class="hljs language-${language}">${hljs.highlight(text, { language }).value}</code></pre>`; } } });
const api = new JarvisApi();
const app = document.querySelector<HTMLDivElement>('#app')!;

function message(role: ChatMessage['role'], content: string, status: ChatMessage['status'] = 'sent'): ChatMessage { return { id: crypto.randomUUID(), role, content, timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), status }; }
function voiceLabel(state: VoiceState): string { return state[0].toUpperCase() + state.slice(1); }
function render(state: AppState): void {
  app.innerHTML = `<main class="shell ${state.sidebarCollapsed ? 'collapsed' : ''}">
    <aside class="sidebar glass"><div class="brand"><div class="brand-mark">J</div><span>JARVIS</span></div>${['New Chat','History','Memory','Settings','Voice','Models','About','Logs'].map(x => `<button class="nav" data-page="${x.toLowerCase().replace(' ','-')}">${x}</button>`).join('')}</aside>
    <section class="workspace"><header class="toolbar glass"><button id="collapse" aria-label="Toggle sidebar">☰</button><div><strong>JARVIS Command Center</strong><span>${voiceLabel(state.voiceState)} · ${state.model}</span></div><div class="toolbar-actions"><span class="pill ${state.backend}">${state.backend}</span><button id="settings">⚙</button></div></header>
    <section class="hero glass"><div class="orb ${state.voiceState}"><span></span></div><div class="wave" aria-label="voice waveform">${Array.from({length:28},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="state">${voiceLabel(state.voiceState)}</div></section>
    <section class="content glass">${renderPage(state)}</section><footer class="status glass"><span>Backend: ${state.backend}</span><span>Internet: ${state.internet?'Online':'Offline'}</span><span>Model: ${state.model}</span><span>Mic: ${state.settings.voiceEnabled?'Ready':'Muted'}</span><span>Speaker: ${state.settings.ttsEnabled?'On':'Off'}</span><span>Firebase: Standby</span><span>Memory: ${state.memory.length}</span><span>CPU: ${state.cpu.toFixed(0)}%</span><span>RAM: ${state.ram} MB</span></footer></section>
    <div class="toasts">${state.notifications.map(n=>`<div class="toast ${n.type}"><strong>${n.title}</strong><span>${n.message}</span></div>`).join('')}</div></main>`;
  bindEvents();
}
function renderPage(state: AppState): string {
 if (state.activePage === 'settings') return `<div class="settings">${['General','Appearance','Voice','Speech Recognition','Text To Speech','AI Models','Memory','Privacy','Firebase','Developer','About'].map(s=>`<article><h3>${s}</h3><p>Configure ${s.toLowerCase()} preferences.</p></article>`).join('')}</div>`;
 if (state.activePage === 'memory') return `<div class="panel"><h2>Memory Viewer</h2><input class="search" placeholder="Search memories"/>${state.memory.map(m=>`<article class="memory"><b>${m.title}</b><p>${m.content}</p><button>Delete</button><button>Export</button></article>`).join('') || '<p class="muted">No memory records returned by backend yet.</p>'}</div>`;
 if (state.activePage === 'logs') return `<div class="panel"><h2>Logs</h2><input class="search" placeholder="Filter information, warnings, errors, API, speech, and system logs"/>${state.logs.map(l=>`<p class="log ${l.level}">[${l.timestamp}] ${l.source}: ${l.message}</p>`).join('') || '<p class="muted">No logs returned by backend yet.</p>'}</div>`;
 return `<div id="chat" class="chat">${state.messages.map(m=>`<article class="message ${m.role}"><div class="bubble">${marked.parse(m.content) as string}<div class="msg-tools"><time>${m.timestamp}</time><button>Copy</button><button>Regenerate</button><button>Edit</button><button>Delete</button></div></div></article>`).join('')}</div><form id="composer" class="composer"><button type="button" id="mic">🎙</button><textarea id="prompt" placeholder="Ask JARVIS anything…" rows="1"></textarea><button type="submit">Send</button></form>`;
}
function bindEvents(): void { document.querySelector('#collapse')?.addEventListener('click',()=>store.set({sidebarCollapsed:!store.state.sidebarCollapsed})); document.querySelector('#settings')?.addEventListener('click',()=>store.set({activePage:'settings'})); document.querySelectorAll<HTMLElement>('.nav').forEach(b=>b.onclick=()=> b.dataset.page === 'new-chat' ? store.set({messages:[],activePage:'chat'}) : store.set({activePage:b.dataset.page ?? 'chat'})); document.querySelector('#composer')?.addEventListener('submit', onSubmit); document.querySelector('#mic')?.addEventListener('click', toggleMic); document.querySelectorAll('.copy-code').forEach(b=>b.addEventListener('click',e=>navigator.clipboard.writeText((e.currentTarget as HTMLElement).nextElementSibling?.textContent ?? ''))); }
async function onSubmit(event: Event): Promise<void> { event.preventDefault(); const input = document.querySelector<HTMLTextAreaElement>('#prompt'); const text = input?.value.trim(); if (!text) return; input!.value=''; store.set({messages:[...store.state.messages, message('user', text)], voiceState:'thinking'}); try { const response = await api.sendMessage(text); store.set({messages:[...store.state.messages, message('assistant', response)], voiceState:'speaking'}); setTimeout(()=>store.set({voiceState:'idle'}),1200); } catch (e) { store.notify({type:'error', title:'Backend unavailable', message:e instanceof Error ? e.message : 'Unable to reach FastAPI'}); store.set({backend:'offline', voiceState:'offline'}); } }
async function toggleMic(): Promise<void> { const listening = store.state.voiceState === 'listening'; store.set({voiceState: listening ? 'recognizing' : 'listening'}); listening ? await api.stopListening() : await api.startListening(); }
async function boot(): Promise<void> { store.subscribe(render); window.addEventListener('online',()=>store.set({internet:true})); window.addEventListener('offline',()=>store.set({internet:false})); try { await invoke('launch_backend'); } catch { store.notify({type:'warning',title:'Backend launch',message:'Sidecar unavailable; trying existing FastAPI server.'}); } const probe = async()=>{ const ok = await api.healthCheck(); store.set({backend: ok ? 'online':'offline'}); }; await probe(); setInterval(probe,5000); setInterval(async()=>{ try { const m = await invoke<{cpu_usage:number;ram_usage:number}>('system_metrics'); store.set({cpu:m.cpu_usage, ram: Math.round(m.ram_usage/1024/1024)}); } catch {} },3000); }
void boot();
